### ISSUE TITLE
Add zh_CN locale to build

### ISSUE THREAD

**Issue by chenweiyj** [nwjs-community/nw-builder#357] opened 2016-08-26 08:35 UTC
Is it possible to point it out in package.json?

**Comment by adam-lynch** [comment] 2016-09-12 21:46
I'm not sure. @evshiron, do you know?

**Comment by evshiron** [comment] 2016-09-13 08:33
Sorry but I have no idea what that "zh_CN locale" means. The files in `locales` directory?

**Comment by nurishi** [comment] 2016-11-03 03:43
I have some input with my findings on this topic.

If it's about OSX sdk build, I guess the root cause is the same as mine which I already have a patch as pull request #389. The issue for me is when we package the app with nw-builder, all the locales directories are deleted which are originally existing in nwjs (Tested with 3.1.2).

My patch is to retain locale directories instead but only deleting files inside so that multi local support is still available to the apps packaged by nw-builder.

 There's nothing you can do in package.json if the locale directories are already dropped off.

If it's about OSX/Win normal builds, the issue will be different and the problem is on nwjs side that it lacks locales folders other than 'en' in their official build(checked with 0.14.7). However, we want nw-builder to always retain the locales regardless of those flavours.

Hope it helps.

**Comment by fritx** [comment] 2016-11-28 12:13
[1128] nw18 解决locale判断失效
https://github.com/nwjs/nw-builder/issues/357
12升18 应用打包后 navigator.language(s)始终返回en
(1) 可以确保nw Resources/下的`*.lproj`语言文件 cp到打包后的app内
language(s)重新生效 像nw12一样

```js
nw.build()
.then(() => {
  // mac
  ;['en', 'zh_CN', 'zh_TW'].forEach(k => {
    const f = `./cache/0.18.8-sdk/osx64/${k}.lproj`
    fs.copySync(f, '../regt-app/osx64/Genius.app/Contents/Resources/')
  })
})
```

(2) 也可以考虑引入os-locale这个库
https://github.com/sindresorhus/os-locale
但它在win上调用的wmic有可能是未加入path 甚至是不存在
需要注意 并且调用耗时

```js
if (IS_WIN) {
  const winPath = process.env.windir || process.env.WINDIR
  const wmicPath = winPath + '\\systm32\\webm'
  process.env.PATH = [wmicPath, process.env.PATH].join(';')
}
try {
  return require('os-locale').sync()
} catch (e) {
  return 'en'
}
```

**Comment by ayushmxn** [comment] 2022-05-18 23:57
@chenweiyj Closing this for now. Let me know if you still want this feature.

**Closed by ayushmxn** 2022-05-18 23:57 UTC
Labels: feature
